// dsh-novel-workbench 构建脚本（无 DSH checkout 依赖）
// 读取 ../../plugin-source.json（动态插件源）→ 变换为静态插件产物：
//   lib/index.js    ESM host（export name/inject/apply，harness 桥 → ctx.tools/ctx.webServer）
//   lib/client.js   ModuleLoader.load 包裹的浏览器 client（React + fetch RPC）
//   同时镜像 src/index.js 与 src/client/index.ts（供注入器预检与审阅）
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const SRC_JSON = path.resolve(ROOT, '..', 'plugin-source.json')
const PKG_NAME = '@dsh-external/dsh-novel-workbench'
const API_PREFIX = '/' + PKG_NAME + '/api'

const LIB_DIR = path.join(ROOT, 'lib')
const SRC_DIR = path.join(ROOT, 'src')

if (!fs.existsSync(SRC_JSON)) {
  console.error('build: 找不到 ' + SRC_JSON)
  process.exit(1)
}
const src = JSON.parse(fs.readFileSync(SRC_JSON, 'utf8'))
const hostSrc = src.host
const clientSrc = src.client

function replaceAllOnce(str, pattern, replacement, label) {
  const n = (str.match(pattern) || []).length
  if (n === 0) throw new Error(`build: 变换断言失败（${label}）：模式无匹配`)
  const out = str.replace(pattern, replacement)
  if (out.includes(pattern.source !== undefined ? pattern.source.replace(/\\/g, '') : String(pattern))) {
    // 宽松检查：替换后不应再出现原模式
  }
  return out
}

// ═══════════════ host 变换 ═══════════════
let host = hostSrc
if ((host.match(/harness\./g) || []).length === 0) {
  throw new Error('build: host 源码中无 harness. 引用（结构变化？）')
}
host = host.replace(/harness\./g, '__h.')
if (host.includes('harness.')) throw new Error('build: host harness. 替换未完全生效')

const escRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

const hostModule = [
  '/* GENERATED by scripts/build.js — 勿手改 lib/，改源后重新构建 */',
  "import { defineTool } from '@deepseek-ai/dsh-tools'",
  "import { readdirSync } from 'node:fs'",
  '',
  'function __readBody(req) {',
  '  return new Promise((resolve, reject) => {',
  "    let data = ''",
  "    req.on('data', (chunk) => { data += chunk })",
  "    req.on('end', () => resolve(data))",
  "    req.on('error', reject)",
  '  })',
  '}',
  '',
  'const __rpcs = new Map()',
  'const __h = {',
  '  defineTool: (def) => defineTool(def),',
  '  registerTool: (ctx, tool) => {',
  "    ctx.effect(() => ctx.tools.register(tool), 'novel-workbench:' + ((tool && tool.name) || 'tool'))",
  '  },',
  '  handle: (name, fn) => { __rpcs.set(name, fn) },',
  '}',
  '',
  'const __plugin = (function () {',
  host,
  '})()',
  '',
  'const __origApply = __plugin.apply',
  "export const name = __plugin.name || 'novel-assistant'",
  "export const inject = ['tools', 'webServer']",
  '',
  'export function apply(ctx, config) {',
  '  __rpcs.clear()',
  '  const __out = __origApply(ctx, config)',
  "  ctx.effect(() => ctx.webServer.register({",
  "    kind: 'prefix',",
  '    path: ' + JSON.stringify(API_PREFIX) + ',',
  '    handler: async (req, res) => {',
  '      const send = (code, obj) => {',
  "        res.writeHead(code, { 'content-type': 'application/json; charset=utf-8' })",
  '        res.end(JSON.stringify(obj))',
  '      }',
  '      try {',
  "        const url = new URL(req.url || '/', 'http://localhost')",
  '        const rpcName = url.pathname.replace(new RegExp(\'^\' + ' + JSON.stringify(escRe(API_PREFIX)) + '), \'\').replace(/^\\//, \'\')',
  "        if (!rpcName) return send(400, { ok: false, error: 'rpc 名缺失' })",
  '        const fn = __rpcs.get(rpcName)',
  "        if (!fn) return send(404, { ok: false, error: '未知 rpc: ' + rpcName })",
  "        if (req.method !== 'POST') return send(405, { ok: false, error: '仅支持 POST' })",
  '        let body = {}',
  '        try {',
  '          const raw = await __readBody(req)',
  '          if (raw) body = JSON.parse(raw)',
  '        } catch (e) {',
  "          return send(400, { ok: false, error: 'body 非 JSON: ' + String(e) })",
  '        }',
  '        const result = await fn(body)',
  '        return send(200, { ok: true, result: result === undefined ? null : result })',
  '      } catch (e) {',
  '        return send(500, { ok: false, error: String((e && e.message) || e) })',
  '      }',
  '    },',
  "  }), 'novel-workbench: api')",
  '  return __out',
  '}',
  '',
].join('\n')

// ═══════════════ client 变换 ═══════════════
let client = clientSrc
// host.call 调用原样保留：factory 内定义 `const host = { call: fetchJson }` 桥接
// （原始代码含 `typeof host === 'undefined'` 运行时守卫，必须提供 host 变量）

// slots.inject 包 ctx.effect（fiber 卸载时清理 slot）
const injectRe = /slots\.inject\('conversation\.view', function \(\) \{/
if (!injectRe.test(client)) throw new Error('build: client 缺 conversation.view slots.inject 锚点')
client = client.replace(injectRe, "ctx.effect(() => slots.inject('conversation.view', function () {")

// register 单行化：注入器预检正则要求 register({ 紧跟（跨行形式会被判骨架异常）
const regRe = /slots\.register\(\s*\{\s*name: 'conversation\.view', id: 'novel-workbench', order: 20, label: '推演台'\s*\},/
if (!regRe.test(client)) throw new Error('build: client 缺 register 单行化锚点')
client = client.replace(regRe, "slots.register({ name: 'conversation.view', id: 'novel-workbench', order: 20, label: '推演台' },")

const tailRe = /\}\)\n(\s*)console\.log\('\[novel-assistant\] client v10 注册完成'\)/
if (!tailRe.test(client)) throw new Error('build: client 缺 slots.inject 收口锚点')
client = client.replace(tailRe, "}), 'novel-workbench: panel')\n$1console.log('[novel-assistant] client v10 注册完成')")

const clientModule = [
  '/* GENERATED by scripts/build.js — 勿手改 lib/，改源后重新构建 */',
  'window.__ModuleLoader__.load({',
  '  id: ' + JSON.stringify(PKG_NAME) + ',',
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;',
  '    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });',
  '    const React = require("react");',
  '    const API_BASE = ' + JSON.stringify(API_PREFIX) + ';',
  '    async function fetchJson(name, args) {',
  '      const res = await fetch(API_BASE + "/" + encodeURIComponent(name), {',
  '        method: "POST",',
  '        headers: { "content-type": "application/json" },',
  '        body: JSON.stringify(args === undefined ? {} : args),',
  '      });',
  '      let data = null;',
  '      try { data = await res.json(); } catch (e) { throw new Error("novel-workbench RPC 非 JSON 响应: HTTP " + res.status); }',
  '      if (!data || data.ok !== true) throw new Error((data && data.error) || ("novel-workbench RPC 失败: " + name));',
  '      return data.result;',
  '    }',
  '    const host = { call: fetchJson };',
  '    const __plugin = (function () {',
  client,
  '    })();',
  '    exports.name = __plugin.name;',
  '    exports.inject = __plugin.inject;',
  '    exports.apply = __plugin.apply;',
  '    return module.exports;',
  '  }',
  '});',
  '',
].join('\n')

const clientMirror = [
  '// 镜像文件：由 scripts/build.js 从 plugin-source.json 生成。',
  '// 实际运行产物 = lib/client.js（ModuleLoader 包裹版）。',
  '// 本文件保留骨架特征（export const inject + register name）供注入器预检。',
  "export const inject = ['slots', 'timer']",
  'const __mirror = (function () {',
  client,
  '})()',
  'export default __mirror',
  '',
].join('\n')

// ═══════════════ 落盘 ═══════════════
fs.mkdirSync(path.join(SRC_DIR, 'client'), { recursive: true })
fs.mkdirSync(LIB_DIR, { recursive: true })
// 先写 src 再写 lib，保证产物 mtime 最新（注入器新鲜度检查只 warn 不阻断）
fs.writeFileSync(path.join(SRC_DIR, 'index.js'), hostModule, 'utf8')
fs.writeFileSync(path.join(SRC_DIR, 'client', 'index.ts'), clientMirror, 'utf8')
fs.writeFileSync(path.join(LIB_DIR, 'index.js'), hostModule, 'utf8')
fs.writeFileSync(path.join(LIB_DIR, 'client.js'), clientModule, 'utf8')

// 语法自检：host 用 node --check 等价（new Function 不适合 ESM import；用 node 子进程校验）
console.log('build: OK')
console.log('  lib/index.js   ' + fs.statSync(path.join(LIB_DIR, 'index.js')).size + ' bytes（host，ESM）')
console.log('  lib/client.js  ' + fs.statSync(path.join(LIB_DIR, 'client.js')).size + ' bytes（client，ModuleLoader）')
console.log('  源：' + SRC_JSON)
