// dsh-novel-workbench 构建脚本（无 DSH checkout 依赖）
// 读取 ../../plugin-source.json（动态插件源）→ 变换为静态插件产物：
//   lib/index.js    ESM host（export name/inject/apply，harness 桥 → ctx.tools/ctx.webServer）
//   lib/client.js   ModuleLoader.load 包裹的浏览器 client（React + fetch RPC）
//   同时镜像 src/index.js 与 src/client/index.ts（供注入器预检与审阅）
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const SRC_JSON = path.resolve(ROOT, '..', 'plugin-source.json')
const PKG_NAME = '@dsh-external/dsh-novel-workbench'
const API_PREFIX = '/' + PKG_NAME + '/api'

// ═══════════════ 单工作区作用域（workspace-scoped）═══════════════
// novel_* 工具与推演台 UI 仅限这些目录树内的会话使用（host 按发起会话 cwd 门控，
// client 按会话 cwd 门控渲染，RPC 按 sessionId 门控）。
// 改动此清单后需重新构建 + dev_reload_package；运行时可用环境变量
// NOVEL_WS_SCOPE（分号分隔，如 "D:\\ds;D:\\other"）覆盖（host 侧，client 侧仍用内置值）。
const WS_SCOPE_DEFAULT = ['D:\\ds']

const LIB_DIR = path.join(ROOT, 'lib')
const SRC_DIR = path.join(ROOT, 'src')

if (!fs.existsSync(SRC_JSON)) {
  console.error('build: 找不到 ' + SRC_JSON)
  process.exit(1)
}
const src = JSON.parse(fs.readFileSync(SRC_JSON, 'utf8'))
const hostSrc = src.host
const clientSrc = src.client

function replaceAllOnce(str, pattern, replacement, label) {
  const n = (str.match(pattern) || []).length
  if (n === 0) throw new Error(`build: 变换断言失败（${label}）：模式无匹配`)
  const out = str.replace(pattern, replacement)
  if (out.includes(pattern.source !== undefined ? pattern.source.replace(/\\/g, '') : String(pattern))) {
    // 宽松检查：替换后不应再出现原模式
  }
  return out
}

// ═══════════════ host 变换 ═══════════════
let host = hostSrc
if ((host.match(/harness\./g) || []).length === 0) {
  throw new Error('build: host 源码中无 harness. 引用（结构变化？）')
}
host = host.replace(/harness\./g, '__h.')
if (host.includes('harness.')) throw new Error('build: host harness. 替换未完全生效')

const escRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

const hostModule = [
  '/* GENERATED by scripts/build.js — 勿手改 lib/，改源后重新构建 */',
  "import { defineTool } from '@deepseek-ai/dsh-tools'",
  "import { readdirSync } from 'node:fs'",
  '',
  'function __readBody(req) {',
  '  return new Promise((resolve, reject) => {',
  "    let data = ''",
  "    req.on('data', (chunk) => { data += chunk })",
  "    req.on('end', () => resolve(data))",
  "    req.on('error', reject)",
  '  })',
  '}',
  '',
  'const __rpcs = new Map()',
  'const __SCOPE = (function () {',
  '  const env = (typeof process !== "undefined" && process.env && process.env.NOVEL_WS_SCOPE) || ""',
  '  const list = env.split(";").map(function (s) { return s.trim() }).filter(Boolean)',
  '  return list.length ? list : ' + JSON.stringify(WS_SCOPE_DEFAULT),
  '})()',
  'function __norm(p) { return String(p || "").replace(/[\\\\/]+$/g, "").toLowerCase() }',
  'function __scopeHit(cwd) {',
  '  if (!cwd) return null',
  '  const n = __norm(cwd)',
  '  for (const d of __SCOPE) {',
  '    const nd = __norm(d)',
  '    if (n === nd || n.startsWith(nd + "\\\\")) return d',
  '  }',
  '  return null',
  '}',
  'function __sessionCwd(ctx) {',
  '  try {',
  '    const agents = ctx && ctx.get("agents")',
  '    if (!agents) return null',
  '    const agent = agents.currentInitiator ? agents.currentInitiator() : null',
  '    if (!agent) return null',
  '    if (agent.cwd) return agent.cwd',
  '    const sess = agent.session || (agent.ctx && agent.ctx.session) || null',
  '    if (sess) {',
  '      const c1 = (sess.header && sess.header.cwd) || (sess.meta && sess.meta.cwd)',
  '      if (c1) return c1',
  '    }',
  '    if (typeof agent.sessionId === "string" && agent.sessionId) {',
  '      const sessions = ctx.get("sessions")',
  '      const s = sessions && sessions.get(agent.sessionId)',
  '      const c2 = s && ((s.header && s.header.cwd) || (s.meta && s.meta.cwd))',
  '      if (c2) return c2',
  '    }',
  '    return null',
  '  } catch (e) { return null }',
  '}',
  // RPC 门控的 cwd 解析（多源）：sessions registry → agents 列表按 sessionId 匹配 → 兜底当前发起者。
  // v13 修复（2026-08-17）：原 RPC 门控只信任 sessions.get(sid).meta/header.cwd，但 DSH 的
  // sessions registry 普遍无 cwd 字段（实测为空），导致所有带 __sid 的请求被 403（含 D:\ds 本会话，
  // client 用 ping 判据后标签全灭）。真实 cwd 在 agent 对象上（__sessionCwd 已证可拿到 D:\ds）。
  'function __rpcCwd(ctx, sid) {',
  '  try {',
  '    const sessions = ctx && ctx.get("sessions")',
  '    const s = sessions && sessions.get ? sessions.get(sid) : null',
  '    if (s) {',
  '      const c = (s.meta && s.meta.cwd) || (s.header && s.header.cwd) || ""',
  '      if (c) return c',
  '    }',
  '    const agents = ctx && ctx.get("agents")',
  '    if (agents && agents.list) {',
  '      const list = agents.list()',
  '      for (const a of list) {',
  '        const aid = (a && (a.sessionId || (a.session && a.session.id))) || ""',
  '        if (aid && String(aid) === String(sid)) {',
  '          const c = (a.cwd) || (a.session && a.session.header && a.session.header.cwd) || (a.session && a.session.meta && a.session.meta.cwd) || ""',
  '          if (c) return c',
  '        }',
  '      }',
  '    }',
  '    return __sessionCwd(ctx)',
  '  } catch (e) { return null }',
  '}',
  'const __h = {',
  '  defineTool: (def) => defineTool(def),',
  '  registerTool: (ctx, tool) => {',
  "    ctx.effect(() => ctx.tools.register(tool), 'novel-workbench:' + ((tool && tool.name) || 'tool'))",
  '  },',
  '  handle: (name, fn) => { __rpcs.set(name, fn) },',
  '}',
  '',
  'const __plugin = (function () {',
  host,
  '})()',
  '',
  'const __origApply = __plugin.apply',
  "export const name = __plugin.name || 'novel-assistant'",
  "export const inject = ['tools', 'webServer']",
  '',
  'export function apply(ctx, config) {',
  '  __rpcs.clear()',
  '  const __out = __origApply(ctx, config)',
  "  ctx.effect(() => ctx.webServer.register({",
  "    kind: 'prefix',",
  '    path: ' + JSON.stringify(API_PREFIX) + ',',
  '    handler: async (req, res) => {',
  '      const send = (code, obj) => {',
  "        res.writeHead(code, { 'content-type': 'application/json; charset=utf-8' })",
  '        res.end(JSON.stringify(obj))',
  '      }',
  '      try {',
  "        const url = new URL(req.url || '/', 'http://localhost')",
  '        const rpcName = url.pathname.replace(new RegExp(\'^\' + ' + JSON.stringify(escRe(API_PREFIX)) + '), \'\').replace(/^\\//, \'\')',
  "        if (!rpcName) return send(400, { ok: false, error: 'rpc 名缺失' })",
  '        const fn = __rpcs.get(rpcName)',
  "        if (!fn) return send(404, { ok: false, error: '未知 rpc: ' + rpcName })",
  "        if (req.method !== 'POST') return send(405, { ok: false, error: '仅支持 POST' })",
  '        let body = {}',
  '        try {',
  '          const raw = await __readBody(req)',
  '          if (raw) body = JSON.parse(raw)',
  '        } catch (e) {',
  "          return send(400, { ok: false, error: 'body 非 JSON: ' + String(e) })",
  '        }',
  '        const sid = (body && typeof body === "object" && body.__sid) ? String(body.__sid) : ""',
  '        if (sid) {',
  '          delete body.__sid',
  '          const cwd = __rpcCwd(ctx, sid) || ""',
  '          if (!__scopeHit(cwd)) return send(403, { ok: false, error: "novel-workbench 仅限工作区 " + __SCOPE.join(" / ") + " 的会话使用（当前会话不在作用域内）" })',
  '        }',
  '        const result = await fn(body)',
  '        return send(200, { ok: true, result: result === undefined ? null : result })',
  '      } catch (e) {',
  '        return send(500, { ok: false, error: String((e && e.message) || e) })',
  '      }',
  '    },',
  "  }), 'novel-workbench: api')",
  '  return __out',
  '}',
  '',
].join('\n')

// ═══════════════ client 变换 ═══════════════
let client = clientSrc
// host.call 调用原样保留：factory 内定义 `const host = { call: fetchJson }` 桥接
// （原始代码含 `typeof host === 'undefined'` 运行时守卫，必须提供 host 变量）

// 单工作区门控（v16 悬浮窗入口，与 dsh-ws-gated-demo 同原理）：
// ① 入口层：conversation.session.header.actions（「条目即组件」槽位）——
//    PushEntry 用 useSessions 读当前会话 cwd，__novelHit 不命中 return null → 按钮整体隐身
//    （零框架补丁依赖，与 demo 一致）。
// ② 展示层：点击后打开**可拖动悬浮窗面板**（类似 StreamFloat 的浮动形态）——
//    非全屏、浮于界面上方，输入框/对话仍可见可操作；可拖动、可关闭。
// ③ 内容层：面板内 Gate 发 ping（带 __sid）→ host 按 cwd 403 门控，失败渲染引导占位；
//    Workbench 原三栏视图 + StreamFloat 流式输出原样承载（props 全量透传）。
const mountRe = /function \(props\) \{ return React\.createElement\(Workbench, props\) \}/
if (!mountRe.test(client)) throw new Error('build: client 缺 Workbench 挂载组件锚点')
client = client.replace(mountRe, [
  'function (props) {',
  '  var _sid = (props && props.sessionId) || ""',
  '  if (host) host.sessionId = _sid',
  '  function PushEntry(p) {',
  '    var useSessions = p && p.useSessions',
  '    var cwd = useSessions ? String(useSessions(function (st) { var r = st.byId[p.sessionId]; return (r && r.cwd) || "" }) || "") : ""',
  '    var open = React.useState(false)',
  '    if (__novelHit(cwd) === null) return null',
  '    return React.createElement("div", { style: { display: "inline-flex", alignItems: "center" } },',
  '      React.createElement("button", {',
  '        style: { padding: "2px 10px", borderRadius: 999, fontSize: 12, cursor: "pointer", border: "1px solid #4f6ef7", background: "#eef1fe", color: "#4f6ef7", fontWeight: 600, whiteSpace: "nowrap" },',
  '        onClick: function () { open[1](true) },',
  '        title: "打开小说推演台（悬浮窗，可边对话边用）",',
  '      }, "推演台"),',
  '      open[0] ? React.createElement(PushPanel, Object.assign({}, p, { onClose: function () { open[1](false) } })) : null,',
  '    )',
  '  }',
  '  function PushPanel(pp) {',
  '    var pos = React.useState({ x: "18vw", y: "8vh", w: "62vw", h: "72vh" })',
  '    var box = React.useState({ ref: null, drag: null })',
  '    var st = pos[0], setSt = pos[1], bb = box[0]',
  '    React.useEffect(function () {',
  '      function mv(e) {',
  '        if (!bb.drag) return',
  '        var el = bb.ref',
  '        if (el) { el.style.left = (e.clientX - bb.drag.dx) + "px"; el.style.top = (e.clientY - bb.drag.dy) + "px" }',
  '      }',
  '      function up() { bb.drag = null }',
  '      window.addEventListener("mousemove", mv)',
  '      window.addEventListener("mouseup", up)',
  '      return function () { window.removeEventListener("mousemove", mv); window.removeEventListener("mouseup", up) }',
  '    }, [])',
  '    function onDown(e) {',
  '      var el = bb.ref',
  '      if (!el) return',
  '      var r = el.getBoundingClientRect()',
  '      bb.drag = { dx: e.clientX - r.left, dy: e.clientY - r.top }',
  '    }',
  '    return React.createElement("div", { ref: function (n) { bb.ref = n }, style: { position: "fixed", left: st.x, top: st.y, width: st.w, height: st.h, zIndex: 1050, background: "#fff", color: "#1f2329", display: "flex", flexDirection: "column", borderRadius: 10, border: "1px solid #d0d5dd", boxShadow: "0 10px 36px rgba(0,0,0,.2)", overflow: "hidden" } },',
  '      React.createElement("div", { style: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "5px 12px", borderBottom: "1px solid #e3e6ea", background: "#f6f7f9", cursor: "move", userSelect: "none", flex: "0 0 auto" }, onMouseDown: onDown },',
  '        React.createElement("span", { style: { fontSize: 12, fontWeight: 700, color: "#4f6ef7" } }, "小说推演台（可拖动 · 即可边对话边使用）"),',
  '        React.createElement("button", { style: { padding: "3px 10px", borderRadius: 6, fontSize: 12, cursor: "pointer", border: "1px solid #d0d5dd", background: "#fff", color: "#1f2329" }, onClick: pp.onClose }, "✕ 关闭"),',
  '      ),',
  '      React.createElement("div", { style: { flex: 1, overflow: "auto", minHeight: 0 } },',
  '        React.createElement(Gate, pp),',
  '      ),',
  '    )',
  '  }',
  '  var Gate = (function () {',
  '    function G(p) {',
  '      React.Component.call(this, p)',
  '      this.state = { show: null, reason: "" }',
  '      this._alive = true',
  '      this._probe = this._probe.bind(this)',
  '    }',
  '    G.prototype = Object.create(React.Component.prototype)',
  '    G.prototype.constructor = G',
  '    G.prototype._probe = function () {',
  '      var self = this',
  '      var sid = (self.props && self.props.sessionId) || ""',
  '      if (host) host.sessionId = sid',
  '      host.call("ping", {}).then(',
  '        function () { if (self._alive) self.setState({ show: true }) },',
  '        function (e) { if (self._alive) self.setState({ show: false, reason: String((e && e.message) || e) }) }',
  '      )',
  '    }',
  '    G.prototype.componentDidMount = function () { this._probe() }',
  '    G.prototype.componentWillUnmount = function () { this._alive = false }',
  '    G.prototype.render = function () {',
  '      if (this.state.show === true) return React.createElement(Workbench, this.props)',
  '      var probing = this.state.show === null',
  '      var reason = this.state.reason || ""',
  '      var guideStyle = {',
  '        padding: "24px 32px",',
  '        margin: 16,',
  '        border: "1px dashed color-mix(in srgb, currentColor 30%, transparent)",',
  '        borderRadius: 8,',
  '        fontSize: 13,',
  '        lineHeight: 1.7,',
  '        color: "var(--dsw-alias-text-tertiary, #8a8f98)",',
  '      }',
  '      return React.createElement("div", { style: guideStyle },',
  '        React.createElement("p", { style: { margin: 0, fontWeight: 600, fontSize: 14, color: "var(--dsw-alias-label-primary, #1f2329)" } },',
  '          probing ? "正在检测当前会话作用域…" : "推演台不可用"',
  '        ),',
  '        probing ? null : React.createElement("p", { style: { margin: "8px 0 0" } },',
  '          reason && reason.indexOf("仅限工作区") >= 0',
  '            ? "推演台仅对 D:\\\\ds 工作区（novel-gm 预设会话）可用。当前会话不在该工作区。"',
  '            : "推演台服务暂时不可用：" + reason',
  '        ),',
  '        probing ? null : React.createElement("p", { style: { margin: "8px 0 0" } }, "提示：请在 D:\\\\ds 工作区新建会话（preset 选 小说推演 GM）后使用推演台。"),',
  '      )',
  '    }',
  '    return G',
  '  })()',
  '  return React.createElement(PushEntry, props)',
  '}',
].join('\n'))

// slots.inject 包 ctx.effect（fiber 卸载时清理 slot）
const injectRe = /slots\.inject\('conversation\.session\.header\.actions', function \(\) \{/
if (!injectRe.test(client)) throw new Error("build: client 缺 conversation.session.header.actions slots.inject 锚点")
client = client.replace(injectRe, "ctx.effect(() => slots.inject('conversation.session.header.actions', function () {")

// register 单行化：保持 name 字面量与 register({ 同锚。
// header.actions 是「条目即组件」槽位：cwd 门控在组件 return null 层完成
// （与 dsh-ws-gated-demo 同原理），label 保持字符串即可，不依赖框架条件 label。
const regRe = /slots\.register\(\s*\{\s*name: 'conversation\.session\.header\.actions', id: 'novel-workbench', order: 99, label: '推演台'\s*\},/
if (!regRe.test(client)) throw new Error('build: client 缺 register 单行化锚点')
client = client.replace(regRe, "slots.register({ name: 'conversation.session.header.actions', id: 'novel-workbench', order: 99, label: '推演台' },")

const tailRe = /\}\)\n(\s*)console\.log\('\[novel-assistant\] client v10 注册完成'\)/
if (!tailRe.test(client)) throw new Error('build: client 缺 slots.inject 收口锚点')
client = client.replace(tailRe, "}), 'novel-workbench: panel')\n$1console.log('[novel-assistant] client v10 注册完成')")

const clientModule = [
  '/* GENERATED by scripts/build.js — 勿手改 lib/，改源后重新构建 */',
  'window.__ModuleLoader__.load({',
  '  id: ' + JSON.stringify(PKG_NAME) + ',',
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;',
  '    Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });',
  '    const React = require("react");',
  '    const API_BASE = ' + JSON.stringify(API_PREFIX) + ';',
  '    const __SCOPE = ' + JSON.stringify(WS_SCOPE_DEFAULT) + ';',
  '    function __norm(p) { return String(p || "").replace(/[\\\\/]+$/g, "").toLowerCase() }',
  '    function __novelHit(cwd) {',
  '      if (!cwd) return null',
  '      const n = __norm(cwd)',
  '      for (let i = 0; i < __SCOPE.length; i++) {',
  '        const nd = __norm(__SCOPE[i])',
  '        if (n === nd || n.indexOf(nd + "\\\\") === 0) return __SCOPE[i]',
  '      }',
  '      return null',
  '    }',
  '    async function fetchJson(name, args) {',
  '      const payload = Object.assign({}, args === undefined ? {} : args);',
  '      if (host && host.sessionId) payload.__sid = host.sessionId;',
  '      const res = await fetch(API_BASE + "/" + encodeURIComponent(name), {',
  '        method: "POST",',
  '        headers: { "content-type": "application/json" },',
  '        body: JSON.stringify(payload),',
  '      });',
  '      let data = null;',
  '      try { data = await res.json(); } catch (e) { throw new Error("novel-workbench RPC 非 JSON 响应: HTTP " + res.status); }',
  '      if (!data || data.ok !== true) throw new Error((data && data.error) || ("novel-workbench RPC 失败: " + name));',
  '      return data.result;',
  '    }',
  '    const host = { call: fetchJson };',
  '    const __plugin = (function () {',
  client,
  '    })();',
  '    exports.name = __plugin.name;',
  '    exports.inject = __plugin.inject;',
  '    exports.apply = __plugin.apply;',
  '    return module.exports;',
  '  }',
  '});',
  '',
].join('\n')

const clientMirror = [
  '// 镜像文件：由 scripts/build.js 从 plugin-source.json 生成。',
  '// 实际运行产物 = lib/client.js（ModuleLoader 包裹版）。',
  '// 本文件保留骨架特征（export const inject + register name）供注入器预检。',
  "export const inject = ['slots', 'timer']",
  'const __mirror = (function () {',
  client,
  '})()',
  'export default __mirror',
  '',
].join('\n')

// ═══════════════ 落盘 ═══════════════
fs.mkdirSync(path.join(SRC_DIR, 'client'), { recursive: true })
fs.mkdirSync(LIB_DIR, { recursive: true })
// 先写 src 再写 lib，保证产物 mtime 最新（注入器新鲜度检查只 warn 不阻断）
fs.writeFileSync(path.join(SRC_DIR, 'index.js'), hostModule, 'utf8')
fs.writeFileSync(path.join(SRC_DIR, 'client', 'index.ts'), clientMirror, 'utf8')
fs.writeFileSync(path.join(LIB_DIR, 'index.js'), hostModule, 'utf8')
fs.writeFileSync(path.join(LIB_DIR, 'client.js'), clientModule, 'utf8')

// 语法自检：host 用 node --check 等价（new Function 不适合 ESM import；用 node 子进程校验）
console.log('build: OK')
console.log('  lib/index.js   ' + fs.statSync(path.join(LIB_DIR, 'index.js')).size + ' bytes（host，ESM）')
console.log('  lib/client.js  ' + fs.statSync(path.join(LIB_DIR, 'client.js')).size + ' bytes（client，ModuleLoader）')
console.log('  源：' + SRC_JSON)
